#!/usr/bin/env python3
"""Record every media file's pixel size so frames can match the original ratio.

Run after adding media: python3 scripts/gen-dims.py  (needs Pillow + imageio-ffmpeg)
Writes src/lib/dims.ts, keyed like "img/c03" and "vid/n12".
"""
import glob, os, re, subprocess
from PIL import Image
import imageio_ffmpeg

root = os.path.join(os.path.dirname(__file__), "..")
media = os.path.join(root, "public/media")
dims = {}
for p in glob.glob(f"{media}/img/*.webp"):
    if p.endswith(".blur.webp"):
        continue
    with Image.open(p) as im:
        dims["img/" + os.path.basename(p)[:-5]] = im.size
exe = imageio_ffmpeg.get_ffmpeg_exe()
for p in glob.glob(f"{media}/vid/*.mp4"):
    out = subprocess.run([exe, "-i", p], capture_output=True, text=True).stderr
    m = re.search(r"Video:.*?(\d{2,5})x(\d{2,5})", out)
    if m:
        dims["vid/" + os.path.basename(p)[:-4]] = (int(m[1]), int(m[2]))

key = lambda k: (k[:4], int(re.sub(r"\D", "", k[4:]) or 0), k)
lines = [f'  "{k}": [{w}, {h}],' for k, (w, h) in sorted(dims.items(), key=lambda kv: key(kv[0]))]
with open(os.path.join(root, "src/lib/dims.ts"), "w") as f:
    f.write("// Generated by scripts/gen-dims.py — pixel size of each media file.\n")
    f.write("export const DIMS: Record<string, [number, number]> = {\n" + "\n".join(lines) + "\n};\n")
print(len(dims), "entries")
